import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto p-6">
        {/* Main heading for the Privacy Policy page */}
        <div className='max-w-2xl mx-auto text-center mb-24'>
            <h1 className="text-5xl font-bold text-orange-600 mb-4">Privacy Policy</h1>

            {/* Introduction paragraph explaining the purpose of the privacy policy */}
            <p className=" mb-6">
                At Omkar's Portfolio Website, your privacy is important to me. 
                This Privacy Policy outlines the types of information I collect, how I use it, and how I safeguard it.
            </p>
        </div>

        {/* Section describing the types of information collected */}
        <h2 className="text-2xl font-semibold text-orange-500 mb-3">Information I Collect</h2>
        <p className=" mb-4">
            I may collect the following information:
        </p>
        <ul className="list-disc list-inside  mb-6">
            {/* Detailed breakdown of collected information */}
            <li><strong>Email Data:</strong> Information you provide when contacting me via email.</li>
            <li><strong>Comments:</strong> Any data submitted through comments or feedback forms.</li>
            <li><strong>Visits:</strong> Website visit data tracked using analytics tools.</li>
            <li><strong>Cookies:</strong> Data generated by cookies for enhancing user experience and analyzing traffic.</li>
        </ul>

        {/* Section on how the collected information is used */}
        <h2 className="text-2xl font-semibold text-orange-500 mb-3">How I Use Your Information</h2>
        <p className=" mb-4">
            The information I collect is used for the following purposes:
        </p>
        <ul className="list-disc list-inside  mb-6">
            <li>Responding to your inquiries or emails.</li>
            <li>Improving website performance and user experience.</li>
            <li>Analyzing website traffic and user behavior to enhance functionality.</li>
        </ul>

        {/* Section explaining user rights */}
        <h2 className="text-2xl font-semibold text-orange-500 mb-3">Your Rights</h2>
        <p className=" mb-4">
            You have the right to:
        </p>
        <ul className="list-disc list-inside  mb-6">
            <li>Access the personal data I hold about you.</li>
            <li>Request modifications or corrections to your personal data.</li>
            <li>Request deletion of your personal data.</li>
        </ul>
        <p className=" mb-6">
            For any concerns or requests, contact me at <a href="/contact" className="text-orange-600 hover:underline">Contact</a> page.
        </p>

        {/* Reference to the separate Cookie Policy page */}
        <h2 className="text-2xl font-semibold text-orange-500 mb-3">Cookie Policy</h2>
        <p className=" mb-6">
            For detailed information about our use of cookies, please see our <a href="/cookies" className="text-orange-600 hover:underline">Cookie Policy</a> page.
        </p>

        {/* Notification about potential updates to the policy */}
        <p className="">
            This Privacy Policy may be updated periodically. Please check back to stay informed about any changes.
        </p>
    </div>
  );
};

export default PrivacyPolicy;
